spring:
  cloud:
    loadbalancer:
      health-check:
        interval: 1s
        path:
          vectortiles: "/"
    gateway:
      routes:
        - id: vectortiles
          uri: lb://vectortiles
          predicates:
            - Path=${gateway-context-path}/vectortiles/**
          filters:
            - StripPrefix=2
